import { Inter } from 'next/font/google'
import '../page.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>Menu Superior</div>
        <div>Menu Lateral</div>
        {children}
      </body>
    </html>
  )
}
